version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: just-now
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules